name: update github pages
on:
  # https://docs.github.com/ja/actions/reference/events-that-trigger-workflows#scheduled-events
  schedule:
    - cron:  '50 * * * *'
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # https://docs.github.com/ja/actions/guides/building-and-testing-java-with-maven
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Execute with Maven
        run: mvn clean compile exec:java

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: hello-github-actions/hello-github-actions.github.io
          publish_branch: main
          publish_dir: ./public
